### ISSUE TITLE
доступ к репе

### ISSUE THREAD

**Issue by tekstain** [saruman9/space_empires_4x_rus_pnp#1]
Привет! 
Я пытался скачать space_empires_4x_rus_pnp, но скачиваемый архив весит немногим больше 100 кб и естественно никакие pdf не открывается. 
Я не умею пользоваться гитхабом, а потому может я что-то делаю не так? Пытался загуглить проблему, но не смог найти вразумительного ответа, потому решил поставить таску :)

**Comment by saruman9** [comment]
Это [проблема GitHub](https://github.com/git-lfs/git-lfs/issues/1322). Пожалуйста, используйте репозиторий на GitLab: https://gitlab.com/saruman9/space_empires_4x_rus_pnp/. Файлы исходных файлов (в том числе PDF, PNG и др.) можно скачать здесь: https://gitlab.com/saruman9/space_empires_4x_rus_pnp/-/releases.
